// Auto-generated — run `pnpm db:types` to regenerate from your Supabase project.
// Do not edit this file manually.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          display_name: string;
          date_of_birth: string;
          age_tier: "minor" | "young_adult";
          city: string | null;
          state: string | null;
          bio: string | null;
          avatar_url: string | null;
          auth_provider: "google" | "apple";
          parental_consent_at: string | null;
          account_status: "active" | "pending_consent" | "suspended" | "banned";
          is_staff: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<
          Database["public"]["Tables"]["users"]["Row"],
          "created_at" | "updated_at"
        > & {
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["users"]["Insert"]>;
      };
      posts: {
        Row: {
          id: string;
          author_id: string;
          content: string;
          post_type: "spirit" | "move" | "community" | "wellness";
          audience: "all_ages" | "adults_only";
          media_url: string | null;
          moderation_status: "pending" | "approved" | "removed" | "flagged";
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<
          Database["public"]["Tables"]["posts"]["Row"],
          "id" | "created_at" | "updated_at"
        > & {
          id?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["posts"]["Insert"]>;
      };
      post_reactions: {
        Row: {
          id: string;
          post_id: string;
          user_id: string;
          reaction_type: string;
          created_at: string;
        };
        Insert: Omit<
          Database["public"]["Tables"]["post_reactions"]["Row"],
          "id" | "created_at"
        > & {
          id?: string;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["post_reactions"]["Insert"]>;
      };
      comments: {
        Row: {
          id: string;
          post_id: string;
          author_id: string;
          content: string;
          moderation_status: "pending" | "approved" | "removed" | "flagged";
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<
          Database["public"]["Tables"]["comments"]["Row"],
          "id" | "created_at" | "updated_at"
        > & {
          id?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["comments"]["Insert"]>;
      };
      rooms: {
        Row: {
          id: string;
          creator_id: string;
          title: string;
          topic: string | null;
          room_type: "all_ages_moderated" | "adults_only";
          status: "scheduled" | "live" | "closed";
          opened_at: string | null;
          closed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<
          Database["public"]["Tables"]["rooms"]["Row"],
          "id" | "created_at" | "updated_at"
        > & {
          id?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["rooms"]["Insert"]>;
      };
      room_participants: {
        Row: {
          id: string;
          room_id: string;
          user_id: string;
          role: "listener" | "speaker" | "moderator";
          joined_at: string;
          left_at: string | null;
        };
        Insert: Omit<
          Database["public"]["Tables"]["room_participants"]["Row"],
          "id" | "joined_at"
        > & {
          id?: string;
          joined_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["room_participants"]["Insert"]>;
      };
      streaks: {
        Row: {
          id: string;
          user_id: string;
          streak_type: "move" | "devotional";
          current_count: number;
          longest_count: number;
          last_activity_date: string | null;
        };
        Insert: Omit<Database["public"]["Tables"]["streaks"]["Row"], "id"> & {
          id?: string;
        };
        Update: Partial<Database["public"]["Tables"]["streaks"]["Insert"]>;
      };
      move_logs: {
        Row: {
          id: string;
          user_id: string;
          plan_id: string;
          completed_at: string;
          duration_minutes: number;
          created_at: string;
        };
        Insert: Omit<
          Database["public"]["Tables"]["move_logs"]["Row"],
          "id" | "created_at"
        > & {
          id?: string;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["move_logs"]["Insert"]>;
      };
      badges: {
        Row: {
          id: string;
          slug: string;
          name: string;
          description: string;
          icon: string;
          created_at: string;
        };
        Insert: Omit<
          Database["public"]["Tables"]["badges"]["Row"],
          "id" | "created_at"
        > & {
          id?: string;
          created_at?: string;
        };
        Update: Partial<Database["public"]["Tables"]["badges"]["Insert"]>;
      };
      user_badges: {
        Row: {
          id: string;
          user_id: string;
          badge_id: string;
          earned_at: string;
        };
        Insert: Omit<Database["public"]["Tables"]["user_badges"]["Row"], "id"> & {
          id?: string;
        };
        Update: Partial<Database["public"]["Tables"]["user_badges"]["Insert"]>;
      };
      moderation_flags: {
        Row: {
          id: string;
          target_type: "post" | "comment" | "room" | "user" | "voice_segment";
          target_id: string;
          flag_source: "automated" | "user_report" | "staff";
          category: "sexual" | "self_harm" | "hate" | "grooming" | "spam" | "other";
          severity: "low" | "medium" | "high" | "critical";
          reporter_id: string | null;
          reviewer_id: string | null;
          outcome:
            | "pending"
            | "approved"
            | "removed"
            | "warned"
            | "escalated"
            | "dismissed";
          notes: string | null;
          created_at: string;
        };
        Insert: Omit<
          Database["public"]["Tables"]["moderation_flags"]["Row"],
          "id" | "created_at"
        > & {
          id?: string;
          created_at?: string;
        };
        Update: Pick<
          Database["public"]["Tables"]["moderation_flags"]["Row"],
          "reviewer_id" | "outcome" | "notes"
        >;
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}
